### ISSUE TITLE
Training with our own dataset

### ISSUE THREAD

**Issue by eyildiz-ugoe** [liyi14/mx-DeepIM#10]
Hi,

Thank you for sharing the great work.

I was wondering the steps we need to follow if we want to use this with our own dataset (not LINEMOD or other ready dataset but our own items so to speak). As far as I understood, we need to following:

1. 3D model of each object of interest
2. Around 1000 RGB images (taken from different perspectives) of each object of interest, and these images should be taken within a region surrounded by aruco markers.
3. Around 300 depth images for each object of interest
3. Ground truth file for each RGB image, containing such:

```
0:
- cam_R_m2c: [0.09630630, 0.99404401, 0.05100790, 0.57332098, -0.01350810, -0.81922001, -0.81365103, 0.10814000, -0.57120699]
  cam_t_m2c: [-105.35775150, -117.52119142, 1014.87701320]
  obj_bb: [244, 150, 44, 58]
  obj_id: 1
```
 4. Info file for each depth image, containing such:

```
0:
  cam_K: [572.4114, 0.0, 325.2611, 0.0, 573.57043, 242.04899, 0.0, 0.0, 1.0]
  depth_scale: 1.0
```

Could you please confirm if these are the only things required for training and testing? If not, could you tell what more is needed? 

And also, do you think the network would work with small, metalic, shiny objects? Would it work in an image such as the one attached for instance? (Given that we have the 3D model of each component in the harddisk, RGB images and etc.) Could the network estimate the pose of the disk or chip or such in that device?
![dsc_3251](https://user-images.githubusercontent.com/35396058/47204251-2c2b1e80-d383-11e8-9c0c-9e0e1cd95f4e.JPG)
